apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp
    spec:
      containers:
        - name: mcp
          image: public.ecr.aws/gravitational/teleport-distroless:18.2.3
          # args:
          #   - start
          #   - -c
          #   - /config/teleport.yaml
          env:
            - name: TELEPORT_ANONYMOUS_TELEMETRY
              value: "1"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - mountPath: /etc/teleport
              name: config
      volumes:
        - name: config
          configMap:
            name: teleport-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-config
  namespace: default
data:
  # The Teleport configuration file used by the mcp deployment.
  # The Deployment mounts this ConfigMap at /config so Teleport will read
  # /config/teleport.yaml when starting.
  teleport.yaml: |
    version: v3
    teleport:
      proxy_server: peter.teleportdemo.com:443
      nodename: mcp-agent
      data_dir: /var/lib/teleport
      auth_token: c9375c874703bf12181f7b8bdb18a910
      log:
        output: stderr
        severity: INFO
        format:
          output: text
    auth_service:
      enabled: false
    ssh_service:
      enabled: false
    proxy_service:
      enabled: false
    app_service:
      enabled: true
      mcp_demo_server: true
